module.exports = {
  INSTITUTE_COLLECTION: "institute",
  PARTNERS_COLLECTION: "partners",
  CLIENTS_COLLECTION: "Clients",
  MEDIA_COLLECTION: "Media",
  LEADERSHIP_COLLECTION: "Leadership",
  AWARDS_COLLECTION: "Awards",
  MILESTONES_COLLECTION: "Milestones",
  BLOG_COLLECTION: "Blog",
  OWN_COLLECTION: "OwnUniversities",
  BUSINESS_PARTNERS_COLLECTION: "BusinessPartners",
  PROJECT_COLLECTION: "project",
  NEWS_EVENTS_COLLECTION: "News",

};
